<a href="https://colab.research.google.com/github/rt-srujan/mlops1-iris/blob/main/first_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load the data
data = load_iris(as_frame=True)
X = data.data         # features: 4 columns
y = data.target       # labels: which species

# Split: 80% for training, 20% for testing
# random_state=42 makes the split reproducible (same split every time)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Total examples: {len(X)}")
print(f"Training examples: {len(X_train)}")
print(f"Test examples: {len(X_test)}")

Total examples: 150
Training examples: 120
Test examples: 30


In [2]:
from sklearn.ensemble import RandomForestClassifier

# Create the model (sliders are random at this point)
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train it: this is where the sliders get adjusted
model.fit(X_train, y_train)

print("Model trained! ✅")

Model trained! ✅


In [3]:
# Predict on the test set (data the model has never seen)
y_pred = model.predict(X_test)

# Compare predictions to actual labels
print("Predictions:", y_pred[:10])
print("Actuals:    ", y_test.values[:10])

Predictions: [0 2 1 1 0 1 0 0 2 1]
Actuals:     [0 2 1 1 0 1 0 0 2 1]


In [4]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Overall accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Test accuracy: {accuracy:.4f}")

# A more detailed breakdown
print("\nClassification report:")
print(classification_report(y_test, y_pred, target_names=data.target_names))

# Where did it get confused?
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred))

Test accuracy: 0.9000

Classification report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.82      0.90      0.86        10
   virginica       0.89      0.80      0.84        10

    accuracy                           0.90        30
   macro avg       0.90      0.90      0.90        30
weighted avg       0.90      0.90      0.90        30

Confusion matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  2  8]]


In [5]:
train_accuracy = accuracy_score(y_train, model.predict(X_train))
print(f"Training accuracy: {train_accuracy:.4f}")
print(f"Test accuracy:     {accuracy:.4f}")

Training accuracy: 1.0000
Test accuracy:     0.9000


In [6]:
import pandas as pd

# A fake new flower: [sepal length, sepal width, petal length, petal width]
new_flower = pd.DataFrame(
    [[5.1, 3.5, 1.4, 0.2]],
    columns=X.columns
)

prediction = model.predict(new_flower)
probability = model.predict_proba(new_flower)

print(f"Predicted species: {data.target_names[prediction[0]]}")
print(f"Confidence per class: {dict(zip(data.target_names, probability[0]))}")

Predicted species: setosa
Confidence per class: {np.str_('setosa'): np.float64(1.0), np.str_('versicolor'): np.float64(0.0), np.str_('virginica'): np.float64(0.0)}


In [7]:
import joblib

# Save it
joblib.dump(model, 'iris_model.pkl')
print("Model saved! ✅")

# Verify by loading it back
loaded_model = joblib.load('iris_model.pkl')
print("Model loaded! ✅")
print(f"Quick test: {loaded_model.predict(new_flower)}")

Model saved! ✅
Model loaded! ✅
Quick test: [0]
